version: "3.2"

volumes:
  grafana_data:
  home:

services:
  rabbitmq:
    build: dev-stack/rabbitmq
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672

  sftp:
    image: atmoz/sftp
    ports:
      - "127.0.0.1:2222:22"
    command: cortex:password:::upload
    volumes:
      - home:/home/cortex

  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./dev-stack/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dev-stack/grafana/provisioning/:/etc/grafana/provisioning/

  pg_prometheus:
    image: timescale/pg_prometheus:latest-pg11
    command: ["postgres", "-csynchronous_commit=off"]
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./dev-stack/pg_prometheus/docker-entrypoint-initdb.d/004-init-cortex-db.sh:/docker-entrypoint-initdb.d/004-init-cortex-db.sh
      - ./db/schema.sql:/schema.sql
    environment:
      POSTGRES_PASSWORD: "password"

  adapter:
    image: timescale/prometheus-postgresql-adapter:latest
    command: ["-pg-host=pg_prometheus", "-pg-password=password", "-pg-prometheus-log-samples"]

  generator:
    build: dev-stack/data-generator
    environment:
      SFTP_HOST: sftp
      SFTP_PORT: 22
      SFTP_USERNAME: cortex
      SFTP_PASSWORD: password
